apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: eshop
    component: rabbitmq
spec:
  type: NodePort
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
      nodePort: 31111
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31112
  selector:
    app: eshop
    component: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
      component: rabbitmq
  template:
    metadata:
      labels:
        app: eshop
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        - containerPort: 15672