apiVersion: v1
kind: Service
metadata:
  name: sql-data
spec:
  selector:
      app: eshop
      component: sql-data
  ports:
  - port: 1433
    targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-data
spec:
  selector:
    matchLabels:
      app: eshop
      component: sql-data
  template:
    metadata:
      labels:
        app: eshop
        component: sql-data
    spec:
      containers:
      - name: sql-data
        image: mcr.microsoft.com/azure-sql-edge:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: MSSQL_PID
            value: Developer
          - name: MSSQL_SA_PASSWORD
            value: Pass@word
