appId                      = "a9c36809-1807-48cc-a027-b12bc79eeac4"
password                   = "X3ACjx6DtomvU.JScnGFcRTt5Hy5OYHbDh"
environment                = "dev"
resource_group_name        = "apollo-rg"
resource_location          = "Southeast Asia"
apollo_aks_name            = "apollo-aks"
apollo_aks_dns_prefix      = "apollo-aks"
apollo_aks_node_count      = 2
apollo_aks_vm_size         = "Standard_D2_v2"
apollo_aks_os_disk_size_gb = 30
