kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-admin
spec:
  type: NodePort
  selector:
    app: eshop
    component: rabbitmq
  ports:
    - port: 15672
      nodePort: 31672
      name: rabbitmq-management-port